// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "Video.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/AutonomousCommand.h"
#include "Subsystems/Climber.h"
#include "Subsystems/DriveTrain.h"
#include "Subsystems/ForwardUltraSonics.h"
#include "Subsystems/GearCarrier.h"
#include "Subsystems/GearPixy.h"
#include "Subsystems/Intake.h"
#include "Subsystems/PerimeterUltraSonics.h"
#include "Subsystems/Pneumatics.h"
#include "Subsystems/ShooterPixy.h"
#include "Subsystems/ShooterWheel.h"
#include "Subsystems/Transmission.h"
#include "Subsystems/VideoStreamer.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"

class Robot : public IterativeRobot {
public:
	std::unique_ptr<Command> autonomousCommand;
	static std::unique_ptr<OI> oi;
	LiveWindow *lw = LiveWindow::GetInstance();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    static std::shared_ptr<DriveTrain> driveTrain;
    static std::shared_ptr<Transmission> transmission;
    static std::shared_ptr<ShooterWheel> shooterWheel;
    static std::shared_ptr<Climber> climber;
    static std::shared_ptr<VideoStreamer> videoStreamer;
    static std::shared_ptr<Intake> intake;
    static std::shared_ptr<GearCarrier> gearCarrier;
    static std::shared_ptr<ShooterPixy> shooterPixy;
    static std::shared_ptr<GearPixy> gearPixy;
    static std::shared_ptr<Pneumatics> pneumatics;
    static std::shared_ptr<ForwardUltraSonics> forwardUltraSonics;
    static std::shared_ptr<PerimeterUltraSonics> perimeterUltraSonics;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    static std::shared_ptr<Video> videoSys;
	virtual void RobotInit();
	virtual void DisabledInit();
	virtual void DisabledPeriodic();
	virtual void AutonomousInit();
	virtual void AutonomousPeriodic();
	virtual void TeleopInit();
	virtual void TeleopPeriodic();
	virtual void TestPeriodic();
};
#endif
