// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "CANTalon.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Subsystems/VideoStreamer.h"
#include "Pixy.h"
#include "I2CXL_MS_EZ.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<CANTalon> driveTrainLeft1;
	static std::shared_ptr<CANTalon> driveTrainLeft2;
	static std::shared_ptr<CANTalon> driveTrainRight1;
	static std::shared_ptr<CANTalon> driveTrainRight2;
	static std::shared_ptr<DoubleSolenoid> transmissionShiftSolenoid;
	static std::shared_ptr<CANTalon> shooterWheelShooter;
	static std::shared_ptr<CANTalon> climberClimbMotor;
	static std::shared_ptr<CANTalon> intakeMotor;
	static std::shared_ptr<Solenoid> gearCarrierGearExtender;
	static std::shared_ptr<Compressor> pneumaticsCompressor;
	static std::shared_ptr<AnalogInput> perimeterUltraSonicsEcho;
	static std::shared_ptr<DigitalOutput> perimeterUltraSonicsStep;
	static std::shared_ptr<DigitalOutput> perimeterUltraSonicsReset;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<VideoStreamer> videoStreamer;
	static std::shared_ptr<PowerDistributionPanel> pDPPowerDistributionPanel;
	static std::shared_ptr<Pixy> Pixy_Shooter;
	static std::shared_ptr<Pixy> Pixy_Gear;
	static std::shared_ptr<I2CXL_EZ> left_fwd_us;
	static std::shared_ptr<I2CXL_EZ> right_fwd_us;

	static void init();
};
#endif
