// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "CANTalon.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::driveTrainLeft1;
std::shared_ptr<CANTalon> RobotMap::driveTrainLeft2;
std::shared_ptr<CANTalon> RobotMap::driveTrainRight1;
std::shared_ptr<CANTalon> RobotMap::driveTrainRight2;
std::shared_ptr<DoubleSolenoid> RobotMap::transmissionShiftSolenoid;
std::shared_ptr<CANTalon> RobotMap::shooterWheelShooter;
std::shared_ptr<CANTalon> RobotMap::climberClimbMotor;
std::shared_ptr<CANTalon> RobotMap::intakeMotor;
std::shared_ptr<Solenoid> RobotMap::gearCarrierGearExtender;
std::shared_ptr<Compressor> RobotMap::pneumaticsCompressor;
std::shared_ptr<AnalogInput> RobotMap::perimeterUltraSonicsEcho;
std::shared_ptr<DigitalOutput> RobotMap::perimeterUltraSonicsStep;
std::shared_ptr<DigitalOutput> RobotMap::perimeterUltraSonicsReset;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<VideoStreamer> RobotMap::videoStreamer;
std::shared_ptr<PowerDistributionPanel> RobotMap::pDPPowerDistributionPanel;
std::shared_ptr<Pixy> RobotMap::Pixy_Shooter;
std::shared_ptr<Pixy> RobotMap::Pixy_Gear;	
std::shared_ptr<I2CXL_EZ> RobotMap::left_fwd_us;	
std::shared_ptr<I2CXL_EZ> RobotMap::right_fwd_us;

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrainLeft1.reset(new CANTalon(1));
    lw->AddActuator("DriveTrain", "Left1", driveTrainLeft1);
    
    driveTrainLeft2.reset(new CANTalon(2));
    lw->AddActuator("DriveTrain", "Left2", driveTrainLeft2);
    
    driveTrainRight1.reset(new CANTalon(3));
    lw->AddActuator("DriveTrain", "Right1", driveTrainRight1);
    
    driveTrainRight2.reset(new CANTalon(4));
    lw->AddActuator("DriveTrain", "Right2", driveTrainRight2);
    
    transmissionShiftSolenoid.reset(new DoubleSolenoid(0, 0, 1));
    lw->AddActuator("Transmission", "ShiftSolenoid", transmissionShiftSolenoid);
    
    shooterWheelShooter.reset(new CANTalon(10));
    lw->AddActuator("ShooterWheel", "Shooter", shooterWheelShooter);
    
    climberClimbMotor.reset(new CANTalon(7));
    lw->AddActuator("Climber", "ClimbMotor", climberClimbMotor);
    
    intakeMotor.reset(new CANTalon(5));
    lw->AddActuator("Intake", "Motor", intakeMotor);
    
    gearCarrierGearExtender.reset(new Solenoid(0, 2));
    lw->AddActuator("GearCarrier", "GearExtender", gearCarrierGearExtender);
    
    pneumaticsCompressor.reset(new Compressor(0));
    
    
    perimeterUltraSonicsEcho.reset(new AnalogInput(0));
    lw->AddSensor("PerimeterUltraSonics", "Echo", perimeterUltraSonicsEcho);
    
    perimeterUltraSonicsStep.reset(new DigitalOutput(0));
    lw->AddActuator("PerimeterUltraSonics", "Step", perimeterUltraSonicsStep);
    
    perimeterUltraSonicsReset.reset(new DigitalOutput(1));
    lw->AddActuator("PerimeterUltraSonics", "Reset", perimeterUltraSonicsReset);
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    pDPPowerDistributionPanel.reset(new PowerDistributionPanel(0));
    lw->AddSensor("PDP", "PowerDistributionPanel", pDPPowerDistributionPanel);

    videoStreamer.reset(new VideoStreamer());

    Pixy_Shooter.reset(new Pixy(0x54));
    Pixy_Shooter->Set_AlignmentOffset(0,0);

    Pixy_Gear.reset(new Pixy(0x55));
    Pixy_Gear->Set_AlignmentOffset(0,0);
    
    left_fwd_us.reset(new I2CXL_EZ(224));
    right_fwd_us.reset(new I2CXL_EZ(226));
}
