// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SHOOTERPIXY_H
#define SHOOTERPIXY_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Pixy.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ShooterPixy: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Pixy> PixySensor;
	float b1h2b2h_ratio; // Target block 1:block 2 height ratio.
	float b1h2gh_ratio;  // Target block 1:gap 1   height ratio.
	float b12b2_error;   // Error margin
	float b1h2g_error;   // Error margin

public:
	ShooterPixy();
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	bool Update();

};

#endif
